/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ChatMessage {
  'sender' : Principal,
  'message' : string,
  'timestamp' : Time,
}
export interface RentalRequest {
  'id' : bigint,
  'renter' : Principal,
  'status' : RentalStatus,
  'created' : Time,
  'endDate' : Time,
  'owner' : Principal,
  'lastUpdated' : Time,
  'toolId' : bigint,
  'startDate' : Time,
}
export type RentalStatus = { 'requested' : null } |
  { 'completed' : null } |
  { 'approved' : null } |
  { 'declined' : null } |
  { 'cancelledByRenter' : null } |
  { 'cancelledByOwner' : null };
export type Time = bigint;
export type ToolCategory = { 'automotive' : null } |
  { 'gardenTools' : null } |
  { 'specialty' : null } |
  { 'powerTools' : null } |
  { 'handTools' : null };
export type ToolCondition = { 'new' : null } |
  { 'gentlyUsed' : null } |
  { 'wellUsed' : null } |
  { 'needsRepair' : null };
export interface ToolListing {
  'id' : bigint,
  'title' : string,
  'created' : Time,
  'owner' : Principal,
  'description' : string,
  'available' : boolean,
  'category' : ToolCategory,
  'dailyPrice' : bigint,
  'securityDeposit' : [] | [bigint],
  'location' : string,
  'photos' : Array<string>,
  'condition' : ToolCondition,
}
export interface UserProfile {
  'id' : Principal,
  'contactInfo' : [] | [string],
  'displayName' : string,
  'joinedAt' : Time,
  'profilePicture' : string,
  'location' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addToolListing' : ActorMethod<
    [
      string,
      ToolCategory,
      string,
      ToolCondition,
      bigint,
      [] | [bigint],
      string,
      Array<string>,
    ],
    bigint
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createOrUpdateProfile' : ActorMethod<
    [string, [] | [string], string, string],
    undefined
  >,
  'editToolListing' : ActorMethod<
    [
      bigint,
      string,
      ToolCategory,
      string,
      ToolCondition,
      bigint,
      [] | [bigint],
      string,
      boolean,
      Array<string>,
    ],
    undefined
  >,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getRentalMessages' : ActorMethod<[bigint], Array<ChatMessage>>,
  'getRentalsForUser' : ActorMethod<
    [],
    { 'rented' : Array<RentalRequest>, 'owned' : Array<RentalRequest> }
  >,
  'getTool' : ActorMethod<[bigint], [] | [ToolListing]>,
  'getToolAvailability' : ActorMethod<[bigint], boolean>,
  'getToolsByOwner' : ActorMethod<[Principal], Array<ToolListing>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'requestRental' : ActorMethod<[bigint, Time, Time], bigint>,
  'searchTools' : ActorMethod<
    [
      [] | [string],
      [] | [ToolCategory],
      [] | [bigint],
      [] | [bigint],
      boolean,
      string,
    ],
    Array<ToolListing>
  >,
  'sendRentalMessage' : ActorMethod<[bigint, string], undefined>,
  'updateRentalStatus' : ActorMethod<
    [bigint, RentalStatus, [] | [string]],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];