/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ToolCategory = IDL.Variant({
  'automotive' : IDL.Null,
  'gardenTools' : IDL.Null,
  'specialty' : IDL.Null,
  'powerTools' : IDL.Null,
  'handTools' : IDL.Null,
});
export const ToolCondition = IDL.Variant({
  'new' : IDL.Null,
  'gentlyUsed' : IDL.Null,
  'wellUsed' : IDL.Null,
  'needsRepair' : IDL.Null,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const GeoCoordinates = IDL.Record({
  'latitude' : IDL.Float64,
  'longitude' : IDL.Float64,
});
export const Time = IDL.Int;
export const UserProfile = IDL.Record({
  'id' : IDL.Principal,
  'contactInfo' : IDL.Opt(IDL.Text),
  'displayName' : IDL.Text,
  'joinedAt' : Time,
  'address' : IDL.Opt(IDL.Text),
  'profilePicture' : IDL.Text,
  'location' : IDL.Text,
  'coordinates' : IDL.Opt(GeoCoordinates),
});
export const CommunityMapProfile = IDL.Record({
  'id' : IDL.Principal,
  'contactInfo' : IDL.Opt(IDL.Text),
  'displayName' : IDL.Text,
  'joinedAt' : Time,
  'isCurrentUser' : IDL.Bool,
  'address' : IDL.Opt(IDL.Text),
  'profilePicture' : IDL.Text,
  'location' : IDL.Text,
  'coordinates' : IDL.Opt(GeoCoordinates),
});
export const ChatMessage = IDL.Record({
  'sender' : IDL.Principal,
  'message' : IDL.Text,
  'timestamp' : Time,
});
export const RentalStatus = IDL.Variant({
  'requested' : IDL.Null,
  'completed' : IDL.Null,
  'approved' : IDL.Null,
  'declined' : IDL.Null,
  'cancelledByRenter' : IDL.Null,
  'cancelledByOwner' : IDL.Null,
});
export const RentalRequest = IDL.Record({
  'id' : IDL.Nat,
  'renter' : IDL.Principal,
  'status' : RentalStatus,
  'created' : Time,
  'endDate' : Time,
  'owner' : IDL.Principal,
  'lastUpdated' : Time,
  'toolId' : IDL.Nat,
  'startDate' : Time,
});
export const ToolListing = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'created' : Time,
  'owner' : IDL.Principal,
  'description' : IDL.Text,
  'available' : IDL.Bool,
  'category' : ToolCategory,
  'dailyPrice' : IDL.Nat,
  'securityDeposit' : IDL.Opt(IDL.Nat),
  'location' : IDL.Text,
  'photos' : IDL.Vec(IDL.Text),
  'condition' : ToolCondition,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addToolListing' : IDL.Func(
      [
        IDL.Text,
        ToolCategory,
        IDL.Text,
        ToolCondition,
        IDL.Nat,
        IDL.Opt(IDL.Nat),
        IDL.Text,
        IDL.Vec(IDL.Text),
      ],
      [IDL.Nat],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createOrUpdateProfile' : IDL.Func(
      [
        IDL.Text,
        IDL.Opt(IDL.Text),
        IDL.Text,
        IDL.Text,
        IDL.Opt(GeoCoordinates),
        IDL.Opt(IDL.Text),
      ],
      [],
      [],
    ),
  'editToolListing' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        ToolCategory,
        IDL.Text,
        ToolCondition,
        IDL.Nat,
        IDL.Opt(IDL.Nat),
        IDL.Text,
        IDL.Bool,
        IDL.Vec(IDL.Text),
      ],
      [],
      [],
    ),
  'geocodeAddress' : IDL.Func([IDL.Text], [GeoCoordinates], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCommunityMapProfiles' : IDL.Func(
      [],
      [IDL.Vec(CommunityMapProfile)],
      ['query'],
    ),
  'getRentalMessages' : IDL.Func([IDL.Nat], [IDL.Vec(ChatMessage)], ['query']),
  'getRentalsForUser' : IDL.Func(
      [],
      [
        IDL.Record({
          'rented' : IDL.Vec(RentalRequest),
          'owned' : IDL.Vec(RentalRequest),
        }),
      ],
      ['query'],
    ),
  'getTool' : IDL.Func([IDL.Nat], [IDL.Opt(ToolListing)], ['query']),
  'getToolAvailability' : IDL.Func([IDL.Nat], [IDL.Bool], ['query']),
  'getToolsByOwner' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(ToolListing)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'requestRental' : IDL.Func([IDL.Nat, Time, Time], [IDL.Nat], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'searchTools' : IDL.Func(
      [
        IDL.Opt(IDL.Text),
        IDL.Opt(ToolCategory),
        IDL.Opt(IDL.Nat),
        IDL.Opt(IDL.Nat),
        IDL.Bool,
        IDL.Text,
      ],
      [IDL.Vec(ToolListing)],
      ['query'],
    ),
  'sendRentalMessage' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'setCoordinatesForCaller' : IDL.Func([GeoCoordinates], [], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'updateRentalStatus' : IDL.Func(
      [IDL.Nat, RentalStatus, IDL.Opt(IDL.Text)],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ToolCategory = IDL.Variant({
    'automotive' : IDL.Null,
    'gardenTools' : IDL.Null,
    'specialty' : IDL.Null,
    'powerTools' : IDL.Null,
    'handTools' : IDL.Null,
  });
  const ToolCondition = IDL.Variant({
    'new' : IDL.Null,
    'gentlyUsed' : IDL.Null,
    'wellUsed' : IDL.Null,
    'needsRepair' : IDL.Null,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const GeoCoordinates = IDL.Record({
    'latitude' : IDL.Float64,
    'longitude' : IDL.Float64,
  });
  const Time = IDL.Int;
  const UserProfile = IDL.Record({
    'id' : IDL.Principal,
    'contactInfo' : IDL.Opt(IDL.Text),
    'displayName' : IDL.Text,
    'joinedAt' : Time,
    'address' : IDL.Opt(IDL.Text),
    'profilePicture' : IDL.Text,
    'location' : IDL.Text,
    'coordinates' : IDL.Opt(GeoCoordinates),
  });
  const CommunityMapProfile = IDL.Record({
    'id' : IDL.Principal,
    'contactInfo' : IDL.Opt(IDL.Text),
    'displayName' : IDL.Text,
    'joinedAt' : Time,
    'isCurrentUser' : IDL.Bool,
    'address' : IDL.Opt(IDL.Text),
    'profilePicture' : IDL.Text,
    'location' : IDL.Text,
    'coordinates' : IDL.Opt(GeoCoordinates),
  });
  const ChatMessage = IDL.Record({
    'sender' : IDL.Principal,
    'message' : IDL.Text,
    'timestamp' : Time,
  });
  const RentalStatus = IDL.Variant({
    'requested' : IDL.Null,
    'completed' : IDL.Null,
    'approved' : IDL.Null,
    'declined' : IDL.Null,
    'cancelledByRenter' : IDL.Null,
    'cancelledByOwner' : IDL.Null,
  });
  const RentalRequest = IDL.Record({
    'id' : IDL.Nat,
    'renter' : IDL.Principal,
    'status' : RentalStatus,
    'created' : Time,
    'endDate' : Time,
    'owner' : IDL.Principal,
    'lastUpdated' : Time,
    'toolId' : IDL.Nat,
    'startDate' : Time,
  });
  const ToolListing = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'created' : Time,
    'owner' : IDL.Principal,
    'description' : IDL.Text,
    'available' : IDL.Bool,
    'category' : ToolCategory,
    'dailyPrice' : IDL.Nat,
    'securityDeposit' : IDL.Opt(IDL.Nat),
    'location' : IDL.Text,
    'photos' : IDL.Vec(IDL.Text),
    'condition' : ToolCondition,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addToolListing' : IDL.Func(
        [
          IDL.Text,
          ToolCategory,
          IDL.Text,
          ToolCondition,
          IDL.Nat,
          IDL.Opt(IDL.Nat),
          IDL.Text,
          IDL.Vec(IDL.Text),
        ],
        [IDL.Nat],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createOrUpdateProfile' : IDL.Func(
        [
          IDL.Text,
          IDL.Opt(IDL.Text),
          IDL.Text,
          IDL.Text,
          IDL.Opt(GeoCoordinates),
          IDL.Opt(IDL.Text),
        ],
        [],
        [],
      ),
    'editToolListing' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          ToolCategory,
          IDL.Text,
          ToolCondition,
          IDL.Nat,
          IDL.Opt(IDL.Nat),
          IDL.Text,
          IDL.Bool,
          IDL.Vec(IDL.Text),
        ],
        [],
        [],
      ),
    'geocodeAddress' : IDL.Func([IDL.Text], [GeoCoordinates], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCommunityMapProfiles' : IDL.Func(
        [],
        [IDL.Vec(CommunityMapProfile)],
        ['query'],
      ),
    'getRentalMessages' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(ChatMessage)],
        ['query'],
      ),
    'getRentalsForUser' : IDL.Func(
        [],
        [
          IDL.Record({
            'rented' : IDL.Vec(RentalRequest),
            'owned' : IDL.Vec(RentalRequest),
          }),
        ],
        ['query'],
      ),
    'getTool' : IDL.Func([IDL.Nat], [IDL.Opt(ToolListing)], ['query']),
    'getToolAvailability' : IDL.Func([IDL.Nat], [IDL.Bool], ['query']),
    'getToolsByOwner' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(ToolListing)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'requestRental' : IDL.Func([IDL.Nat, Time, Time], [IDL.Nat], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'searchTools' : IDL.Func(
        [
          IDL.Opt(IDL.Text),
          IDL.Opt(ToolCategory),
          IDL.Opt(IDL.Nat),
          IDL.Opt(IDL.Nat),
          IDL.Bool,
          IDL.Text,
        ],
        [IDL.Vec(ToolListing)],
        ['query'],
      ),
    'sendRentalMessage' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'setCoordinatesForCaller' : IDL.Func([GeoCoordinates], [], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'updateRentalStatus' : IDL.Func(
        [IDL.Nat, RentalStatus, IDL.Opt(IDL.Text)],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };