/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface ToolListing {
    id: bigint;
    title: string;
    created: Time;
    owner: Principal;
    description: string;
    available: boolean;
    category: ToolCategory;
    dailyPrice: bigint;
    securityDeposit?: bigint;
    location: string;
    photos: Array<string>;
    condition: ToolCondition;
}
export type Time = bigint;
export interface RentalRequest {
    id: bigint;
    renter: Principal;
    status: RentalStatus;
    created: Time;
    endDate: Time;
    owner: Principal;
    lastUpdated: Time;
    toolId: bigint;
    startDate: Time;
}
export interface GeoCoordinates {
    latitude: number;
    longitude: number;
}
export interface ChatMessage {
    sender: Principal;
    message: string;
    timestamp: Time;
}
export interface CommunityMapProfile {
    id: Principal;
    contactInfo?: string;
    displayName: string;
    joinedAt: Time;
    profilePicture: string;
    location: string;
    coordinates?: GeoCoordinates;
}
export interface UserProfile {
    id: Principal;
    contactInfo?: string;
    displayName: string;
    joinedAt: Time;
    publicCoordinates?: GeoCoordinates;
    profilePicture: string;
    location: string;
    streetAddress?: string;
    coordinates?: GeoCoordinates;
}
export enum RentalStatus {
    requested = "requested",
    completed = "completed",
    approved = "approved",
    declined = "declined",
    cancelledByRenter = "cancelledByRenter",
    cancelledByOwner = "cancelledByOwner"
}
export enum ToolCategory {
    automotive = "automotive",
    gardenTools = "gardenTools",
    specialty = "specialty",
    powerTools = "powerTools",
    handTools = "handTools"
}
export enum ToolCondition {
    new_ = "new",
    gentlyUsed = "gentlyUsed",
    wellUsed = "wellUsed",
    needsRepair = "needsRepair"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addToolListing(title: string, category: ToolCategory, description: string, condition: ToolCondition, dailyPrice: bigint, securityDeposit: bigint | null, location: string, photos: Array<string>): Promise<bigint>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createOrUpdateProfile(displayName: string, contactInfo: string | null, location: string, profilePicture: string, coordinates: GeoCoordinates | null, streetAddress: string | null): Promise<void>;
    editToolListing(toolId: bigint, title: string, category: ToolCategory, description: string, condition: ToolCondition, dailyPrice: bigint, securityDeposit: bigint | null, location: string, available: boolean, photos: Array<string>): Promise<void>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getCommunityMapProfiles(): Promise<Array<CommunityMapProfile>>;
    getRentalMessages(rentalId: bigint): Promise<Array<ChatMessage>>;
    getRentalsForUser(): Promise<{
        rented: Array<RentalRequest>;
        owned: Array<RentalRequest>;
    }>;
    getTool(toolId: bigint): Promise<ToolListing | null>;
    getToolAvailability(toolId: bigint): Promise<boolean>;
    getToolsByOwner(owner: Principal): Promise<Array<ToolListing>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    requestRental(toolId: bigint, startDate: Time, endDate: Time): Promise<bigint>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    searchTools(searchText: string | null, category: ToolCategory | null, minPrice: bigint | null, maxPrice: bigint | null, availableOnly: boolean, sortBy: string): Promise<Array<ToolListing>>;
    sendRentalMessage(rentalId: bigint, message: string): Promise<void>;
    updateRentalStatus(rentalId: bigint, newStatus: RentalStatus, _comments: string | null): Promise<void>;
}
import type { CommunityMapProfile as _CommunityMapProfile, GeoCoordinates as _GeoCoordinates, RentalRequest as _RentalRequest, RentalStatus as _RentalStatus, Time as _Time, ToolCategory as _ToolCategory, ToolCondition as _ToolCondition, ToolListing as _ToolListing, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addToolListing(arg0: string, arg1: ToolCategory, arg2: string, arg3: ToolCondition, arg4: bigint, arg5: bigint | null, arg6: string, arg7: Array<string>): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addToolListing(arg0, to_candid_ToolCategory_n1(this._uploadFile, this._downloadFile, arg1), arg2, to_candid_ToolCondition_n3(this._uploadFile, this._downloadFile, arg3), arg4, to_candid_opt_n5(this._uploadFile, this._downloadFile, arg5), arg6, arg7);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addToolListing(arg0, to_candid_ToolCategory_n1(this._uploadFile, this._downloadFile, arg1), arg2, to_candid_ToolCondition_n3(this._uploadFile, this._downloadFile, arg3), arg4, to_candid_opt_n5(this._uploadFile, this._downloadFile, arg5), arg6, arg7);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n6(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n6(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createOrUpdateProfile(arg0: string, arg1: string | null, arg2: string, arg3: string, arg4: GeoCoordinates | null, arg5: string | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createOrUpdateProfile(arg0, to_candid_opt_n8(this._uploadFile, this._downloadFile, arg1), arg2, arg3, to_candid_opt_n9(this._uploadFile, this._downloadFile, arg4), to_candid_opt_n8(this._uploadFile, this._downloadFile, arg5));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createOrUpdateProfile(arg0, to_candid_opt_n8(this._uploadFile, this._downloadFile, arg1), arg2, arg3, to_candid_opt_n9(this._uploadFile, this._downloadFile, arg4), to_candid_opt_n8(this._uploadFile, this._downloadFile, arg5));
            return result;
        }
    }
    async editToolListing(arg0: bigint, arg1: string, arg2: ToolCategory, arg3: string, arg4: ToolCondition, arg5: bigint, arg6: bigint | null, arg7: string, arg8: boolean, arg9: Array<string>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.editToolListing(arg0, arg1, to_candid_ToolCategory_n1(this._uploadFile, this._downloadFile, arg2), arg3, to_candid_ToolCondition_n3(this._uploadFile, this._downloadFile, arg4), arg5, to_candid_opt_n5(this._uploadFile, this._downloadFile, arg6), arg7, arg8, arg9);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.editToolListing(arg0, arg1, to_candid_ToolCategory_n1(this._uploadFile, this._downloadFile, arg2), arg3, to_candid_ToolCondition_n3(this._uploadFile, this._downloadFile, arg4), arg5, to_candid_opt_n5(this._uploadFile, this._downloadFile, arg6), arg7, arg8, arg9);
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCommunityMapProfiles(): Promise<Array<CommunityMapProfile>> {
        if (this.processError) {
            try {
                const result = await this.actor.getCommunityMapProfiles();
                return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCommunityMapProfiles();
            return from_candid_vec_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getRentalMessages(arg0: bigint): Promise<Array<ChatMessage>> {
        if (this.processError) {
            try {
                const result = await this.actor.getRentalMessages(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRentalMessages(arg0);
            return result;
        }
    }
    async getRentalsForUser(): Promise<{
        rented: Array<RentalRequest>;
        owned: Array<RentalRequest>;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getRentalsForUser();
                return from_candid_record_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getRentalsForUser();
            return from_candid_record_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTool(arg0: bigint): Promise<ToolListing | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getTool(arg0);
                return from_candid_opt_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTool(arg0);
            return from_candid_opt_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async getToolAvailability(arg0: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.getToolAvailability(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getToolAvailability(arg0);
            return result;
        }
    }
    async getToolsByOwner(arg0: Principal): Promise<Array<ToolListing>> {
        if (this.processError) {
            try {
                const result = await this.actor.getToolsByOwner(arg0);
                return from_candid_vec_n34(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getToolsByOwner(arg0);
            return from_candid_vec_n34(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async requestRental(arg0: bigint, arg1: Time, arg2: Time): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.requestRental(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.requestRental(arg0, arg1, arg2);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n35(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n35(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async searchTools(arg0: string | null, arg1: ToolCategory | null, arg2: bigint | null, arg3: bigint | null, arg4: boolean, arg5: string): Promise<Array<ToolListing>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchTools(to_candid_opt_n8(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n37(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n5(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n5(this._uploadFile, this._downloadFile, arg3), arg4, arg5);
                return from_candid_vec_n34(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchTools(to_candid_opt_n8(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n37(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n5(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n5(this._uploadFile, this._downloadFile, arg3), arg4, arg5);
            return from_candid_vec_n34(this._uploadFile, this._downloadFile, result);
        }
    }
    async sendRentalMessage(arg0: bigint, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.sendRentalMessage(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.sendRentalMessage(arg0, arg1);
            return result;
        }
    }
    async updateRentalStatus(arg0: bigint, arg1: RentalStatus, arg2: string | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateRentalStatus(arg0, to_candid_RentalStatus_n38(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n8(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateRentalStatus(arg0, to_candid_RentalStatus_n38(this._uploadFile, this._downloadFile, arg1), to_candid_opt_n8(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
}
function from_candid_CommunityMapProfile_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CommunityMapProfile): CommunityMapProfile {
    return from_candid_record_n19(_uploadFile, _downloadFile, value);
}
function from_candid_RentalRequest_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RentalRequest): RentalRequest {
    return from_candid_record_n23(_uploadFile, _downloadFile, value);
}
function from_candid_RentalStatus_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _RentalStatus): RentalStatus {
    return from_candid_variant_n25(_uploadFile, _downloadFile, value);
}
function from_candid_ToolCategory_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ToolCategory): ToolCategory {
    return from_candid_variant_n30(_uploadFile, _downloadFile, value);
}
function from_candid_ToolCondition_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ToolCondition): ToolCondition {
    return from_candid_variant_n33(_uploadFile, _downloadFile, value);
}
function from_candid_ToolListing_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ToolListing): ToolListing {
    return from_candid_record_n28(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n12(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n16(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n11(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_GeoCoordinates]): GeoCoordinates | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ToolListing]): ToolListing | null {
    return value.length === 0 ? null : from_candid_ToolListing_n27(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: Principal;
    contactInfo: [] | [string];
    displayName: string;
    joinedAt: _Time;
    publicCoordinates: [] | [_GeoCoordinates];
    profilePicture: string;
    location: string;
    streetAddress: [] | [string];
    coordinates: [] | [_GeoCoordinates];
}): {
    id: Principal;
    contactInfo?: string;
    displayName: string;
    joinedAt: Time;
    publicCoordinates?: GeoCoordinates;
    profilePicture: string;
    location: string;
    streetAddress?: string;
    coordinates?: GeoCoordinates;
} {
    return {
        id: value.id,
        contactInfo: record_opt_to_undefined(from_candid_opt_n13(_uploadFile, _downloadFile, value.contactInfo)),
        displayName: value.displayName,
        joinedAt: value.joinedAt,
        publicCoordinates: record_opt_to_undefined(from_candid_opt_n14(_uploadFile, _downloadFile, value.publicCoordinates)),
        profilePicture: value.profilePicture,
        location: value.location,
        streetAddress: record_opt_to_undefined(from_candid_opt_n13(_uploadFile, _downloadFile, value.streetAddress)),
        coordinates: record_opt_to_undefined(from_candid_opt_n14(_uploadFile, _downloadFile, value.coordinates))
    };
}
function from_candid_record_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: Principal;
    contactInfo: [] | [string];
    displayName: string;
    joinedAt: _Time;
    profilePicture: string;
    location: string;
    coordinates: [] | [_GeoCoordinates];
}): {
    id: Principal;
    contactInfo?: string;
    displayName: string;
    joinedAt: Time;
    profilePicture: string;
    location: string;
    coordinates?: GeoCoordinates;
} {
    return {
        id: value.id,
        contactInfo: record_opt_to_undefined(from_candid_opt_n13(_uploadFile, _downloadFile, value.contactInfo)),
        displayName: value.displayName,
        joinedAt: value.joinedAt,
        profilePicture: value.profilePicture,
        location: value.location,
        coordinates: record_opt_to_undefined(from_candid_opt_n14(_uploadFile, _downloadFile, value.coordinates))
    };
}
function from_candid_record_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    rented: Array<_RentalRequest>;
    owned: Array<_RentalRequest>;
}): {
    rented: Array<RentalRequest>;
    owned: Array<RentalRequest>;
} {
    return {
        rented: from_candid_vec_n21(_uploadFile, _downloadFile, value.rented),
        owned: from_candid_vec_n21(_uploadFile, _downloadFile, value.owned)
    };
}
function from_candid_record_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    renter: Principal;
    status: _RentalStatus;
    created: _Time;
    endDate: _Time;
    owner: Principal;
    lastUpdated: _Time;
    toolId: bigint;
    startDate: _Time;
}): {
    id: bigint;
    renter: Principal;
    status: RentalStatus;
    created: Time;
    endDate: Time;
    owner: Principal;
    lastUpdated: Time;
    toolId: bigint;
    startDate: Time;
} {
    return {
        id: value.id,
        renter: value.renter,
        status: from_candid_RentalStatus_n24(_uploadFile, _downloadFile, value.status),
        created: value.created,
        endDate: value.endDate,
        owner: value.owner,
        lastUpdated: value.lastUpdated,
        toolId: value.toolId,
        startDate: value.startDate
    };
}
function from_candid_record_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    title: string;
    created: _Time;
    owner: Principal;
    description: string;
    available: boolean;
    category: _ToolCategory;
    dailyPrice: bigint;
    securityDeposit: [] | [bigint];
    location: string;
    photos: Array<string>;
    condition: _ToolCondition;
}): {
    id: bigint;
    title: string;
    created: Time;
    owner: Principal;
    description: string;
    available: boolean;
    category: ToolCategory;
    dailyPrice: bigint;
    securityDeposit?: bigint;
    location: string;
    photos: Array<string>;
    condition: ToolCondition;
} {
    return {
        id: value.id,
        title: value.title,
        created: value.created,
        owner: value.owner,
        description: value.description,
        available: value.available,
        category: from_candid_ToolCategory_n29(_uploadFile, _downloadFile, value.category),
        dailyPrice: value.dailyPrice,
        securityDeposit: record_opt_to_undefined(from_candid_opt_n31(_uploadFile, _downloadFile, value.securityDeposit)),
        location: value.location,
        photos: value.photos,
        condition: from_candid_ToolCondition_n32(_uploadFile, _downloadFile, value.condition)
    };
}
function from_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    requested: null;
} | {
    completed: null;
} | {
    approved: null;
} | {
    declined: null;
} | {
    cancelledByRenter: null;
} | {
    cancelledByOwner: null;
}): RentalStatus {
    return "requested" in value ? RentalStatus.requested : "completed" in value ? RentalStatus.completed : "approved" in value ? RentalStatus.approved : "declined" in value ? RentalStatus.declined : "cancelledByRenter" in value ? RentalStatus.cancelledByRenter : "cancelledByOwner" in value ? RentalStatus.cancelledByOwner : value;
}
function from_candid_variant_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    automotive: null;
} | {
    gardenTools: null;
} | {
    specialty: null;
} | {
    powerTools: null;
} | {
    handTools: null;
}): ToolCategory {
    return "automotive" in value ? ToolCategory.automotive : "gardenTools" in value ? ToolCategory.gardenTools : "specialty" in value ? ToolCategory.specialty : "powerTools" in value ? ToolCategory.powerTools : "handTools" in value ? ToolCategory.handTools : value;
}
function from_candid_variant_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    new: null;
} | {
    gentlyUsed: null;
} | {
    wellUsed: null;
} | {
    needsRepair: null;
}): ToolCondition {
    return "new" in value ? ToolCondition.new : "gentlyUsed" in value ? ToolCondition.gentlyUsed : "wellUsed" in value ? ToolCondition.wellUsed : "needsRepair" in value ? ToolCondition.needsRepair : value;
}
function from_candid_vec_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_CommunityMapProfile>): Array<CommunityMapProfile> {
    return value.map((x)=>from_candid_CommunityMapProfile_n18(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_RentalRequest>): Array<RentalRequest> {
    return value.map((x)=>from_candid_RentalRequest_n22(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ToolListing>): Array<ToolListing> {
    return value.map((x)=>from_candid_ToolListing_n27(_uploadFile, _downloadFile, x));
}
function to_candid_RentalStatus_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: RentalStatus): _RentalStatus {
    return to_candid_variant_n39(_uploadFile, _downloadFile, value);
}
function to_candid_ToolCategory_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ToolCategory): _ToolCategory {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_ToolCondition_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ToolCondition): _ToolCondition {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_UserProfile_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n36(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n7(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ToolCategory | null): [] | [_ToolCategory] {
    return value === null ? candid_none() : candid_some(to_candid_ToolCategory_n1(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: bigint | null): [] | [bigint] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: GeoCoordinates | null): [] | [_GeoCoordinates] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: Principal;
    contactInfo?: string;
    displayName: string;
    joinedAt: Time;
    publicCoordinates?: GeoCoordinates;
    profilePicture: string;
    location: string;
    streetAddress?: string;
    coordinates?: GeoCoordinates;
}): {
    id: Principal;
    contactInfo: [] | [string];
    displayName: string;
    joinedAt: _Time;
    publicCoordinates: [] | [_GeoCoordinates];
    profilePicture: string;
    location: string;
    streetAddress: [] | [string];
    coordinates: [] | [_GeoCoordinates];
} {
    return {
        id: value.id,
        contactInfo: value.contactInfo ? candid_some(value.contactInfo) : candid_none(),
        displayName: value.displayName,
        joinedAt: value.joinedAt,
        publicCoordinates: value.publicCoordinates ? candid_some(value.publicCoordinates) : candid_none(),
        profilePicture: value.profilePicture,
        location: value.location,
        streetAddress: value.streetAddress ? candid_some(value.streetAddress) : candid_none(),
        coordinates: value.coordinates ? candid_some(value.coordinates) : candid_none()
    };
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ToolCategory): {
    automotive: null;
} | {
    gardenTools: null;
} | {
    specialty: null;
} | {
    powerTools: null;
} | {
    handTools: null;
} {
    return value == ToolCategory.automotive ? {
        automotive: null
    } : value == ToolCategory.gardenTools ? {
        gardenTools: null
    } : value == ToolCategory.specialty ? {
        specialty: null
    } : value == ToolCategory.powerTools ? {
        powerTools: null
    } : value == ToolCategory.handTools ? {
        handTools: null
    } : value;
}
function to_candid_variant_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: RentalStatus): {
    requested: null;
} | {
    completed: null;
} | {
    approved: null;
} | {
    declined: null;
} | {
    cancelledByRenter: null;
} | {
    cancelledByOwner: null;
} {
    return value == RentalStatus.requested ? {
        requested: null
    } : value == RentalStatus.completed ? {
        completed: null
    } : value == RentalStatus.approved ? {
        approved: null
    } : value == RentalStatus.declined ? {
        declined: null
    } : value == RentalStatus.cancelledByRenter ? {
        cancelledByRenter: null
    } : value == RentalStatus.cancelledByOwner ? {
        cancelledByOwner: null
    } : value;
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ToolCondition): {
    new: null;
} | {
    gentlyUsed: null;
} | {
    wellUsed: null;
} | {
    needsRepair: null;
} {
    return value == ToolCondition.new ? {
        new_: null
    } : value == ToolCondition.gentlyUsed ? {
        gentlyUsed: null
    } : value == ToolCondition.wellUsed ? {
        wellUsed: null
    } : value == ToolCondition.needsRepair ? {
        needsRepair: null
    } : value;
}
function to_candid_variant_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
